# Generated by Django 2.2.5 on 2019-10-26 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('client', models.CharField(max_length=100)),
                ('managerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ticketlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('Tickettype', models.CharField(max_length=100)),
                ('Ticketsubtype', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(max_length=600)),
                ('attachment', models.FileField(upload_to='')),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ticketHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('Tickettype', models.CharField(max_length=100)),
                ('Ticketsubtype', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(max_length=600)),
                ('attachment', models.FileField(upload_to='')),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.project'),
        ),
    ]
