# Generated by Django 2.2.5 on 2019-10-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketheader_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.project'),
        ),
    ]
