# Generated by Django 2.2.5 on 2019-10-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketlog_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketheader',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.project'),
        ),
    ]
