# Generated by Django 2.2.5 on 2019-10-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketheader_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='Ticketsubtype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='Tickettype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='comments',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
