# Generated by Django 2.2.5 on 2019-10-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20191026_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketheader',
            name='Ticketsubtype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
