# Generated by Django 2.2.5 on 2019-10-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20191027_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketheader',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'work in progress'), ('3', 'pending for customer side'), ('4', 'Solution Proposed'), ('5', 'Closed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'work in progress'), ('3', 'pending for customer side'), ('4', 'Solution Proposed'), ('5', 'Closed')], max_length=50),
        ),
    ]
