# Generated by Django 2.2.5 on 2019-10-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20191027_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketheader',
            name='Ticketsubtype',
        ),
        migrations.AlterField(
            model_name='ticketheader',
            name='Tickettype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
