# Generated by Django 2.2.5 on 2019-10-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20191027_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketheader',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
