# Generated by Django 2.2.5 on 2019-11-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20191028_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketheader',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
